---
title: Blogs
bibliography: refs.bib
---

Here are the blogs where I share my thoughts and notes on various topics.

## LLM for Theorem Proving

CCF软件工程专业委员会首批发布的三个重要难题之一：自动程序定理证明（如何高度自动化地生成程序定理的形式化证明？）<br>
One of the three key challenges initially released by the CCF Technical Committee of Software Engineering: Automated Program Theorem Proving (How can formal proofs of program theorems be generated in a highly automated manner?)

- SeedProver: [@chen2025seedproverdeepbroadreasoning]
  - Lemma-Style Proving: 分解任务, 独立验证, 构建知识库, 组合证明.
  - Test-Time Scaling
    - Light: Proof Sketch → Lean → Error Feedback → Refine
    - Medium: Outer Loop for main theorem, Inner Loop for hard lemmas.
    - Heavy: Conjecture Proposer (Conjecture Pool) → Light Prover → Lemma Pool → Evaluate → Select High-Quality Lemmas, let Medium Prover prove main theorem again.
  - IMO 2025: 4/6 problems solved.

In my opinion, some *agent techniques* can be *helpful* for theorem proving as well, so I may record some notes of agent papers here:

- Live-SWE-Agent: [@xia2025livesweagentsoftwareengineeringagents]
  - the first *live* software agent that can autonomously and continuously evolve itself *on-the-fly during runtime*
  - starts with *the most basic* agent scaffold with only access to `bash` tools
  - autonomously *evolves* its own scaffold implementation
  - 75.4% in SWE-bench Verified; 45.8% in SWE-Bench Pro. (SOTA in 2025.11)
  - Q: What are the tools in Coq/Lean that can help us evolve the proof strategies on-the-fly during proof construction?
    - the necessary helper lemmas 
    - Reducing to only necessary hypotheses that imply the goal [@brendel2025dilemma]

## Formal Methods in AI

### Static Analysis for DL Architectures

- DEBAR: [Detecting numerical bugs in neural network architectures](./Blogs/FSE20.qmd) [@FSE20Zhang]
  - Affine Relations Abstract Domain.
  - Tensor Partitioning.
- RANUM: [Reliability Assurance for Deep Neural Network Architectures Against Numerical Defects](./Blogs/ICSE23.qmd) [@ICSE23Li]
  - Potential-Defect Detection via Static Analysis.
  - Feasibility Confirmation via Two-Step Test Generation.
  - Fix Suggestion via Abstract Optimization.


### Static Analysis for DL Models

- Use SMT solvers to verify properties of DL models.
- Use integer programming to verify robustness of DL models.
- Abstract interpretation for DL models. (e.g., $\text{AI}^2$, DeepPoly, etc.)
  - Zonotope abstract domain.

SOTA tools:

- $\alpha,\beta$-CROWN

## Dafny Blogs

- [Two quantifiers in a specification](Blogs/Dafny_two_quantifiers.qmd)

## Others

- A brief note about [Dataflow Analysis](./Blogs/DataflowAnalysis.qmd)
