---
title: "Course Notes"
---

Here are the course notes written by myself. I've taken 67 courses (170 points) in PKU.

# 25-26-1

9 courses, 23 points in total.

- Mathmatical Logic | [Click here to view the notes.](./Course_Notes/数理逻辑/数理逻辑.qmd) <br>
  数理逻辑 | [点击此处查看笔记.](./Course_Notes/数理逻辑/数理逻辑.qmd)
- Set Theory and Graph Theory | [Click here to view the notes.](./PDF/图论期末复习.pdf) <br>
  集合论与图论 | [点击此处查看笔记.](./PDF/图论期末复习.pdf)
- Shadowboxing <br>
  太极拳
- Frontiers of Economics Research and Practice <br>
  经济学学术与实践前沿
- Money and Banking <br>
  货币银行学
- International Finance | [Click here to view the notes.](./Course_Notes/国际金融/国际金融.md) <br>
  国际金融 | [点击此处查看笔记.](./Course_Notes/国际金融/国际金融.md)
- Behavioral Economics | [Click here to view the notes.](./PDF/行为经济学期末复习.pdf) <br>
  行为经济学 | [点击此处查看笔记.](./PDF/行为经济学期末复习.pdf)
- Investment <br>
  投资学
- The Economics of Artificial Intelligence <br>
  人工智能经济学

# 24-25-3

2 courses, 4 points in total.

- Topics in Quantitative Finance | [Click here to view the website.](https://vectorpikachu.github.io/qf-slides/) <br>
  量化金融专题 | [点击此处访问网站.](https://vectorpikachu.github.io/qf-slides/)
- Inter-cultural Communication <br>
  跨文化交流学

# 24-25-2

8 courses, 20 points in total.

- Introduction to Database Systems | [Click here to view the PDF.](./PDF/Database.pdf) <br>
  数据库概论 | [点击此处查看PDF.](./PDF/Database.pdf)
- Public Intermediate German <br>
  公共中级德语
  - [The notes. 课程笔记.](./PDF/25春季公共中级德语笔记.pdf)
  - [The tests. 课程小测.](./PDF/公共中级德语小测.pdf)
  - [The words. 课程单词.](./PDF/Einheit 6-10 单词笔记.pdf)
  - Here are two passages full of grammer mistakes: [Ein Programmierer](./PDF/职业描述.pdf) and [Meine Ferien](./PDF/假期描述.pdf).
- Special Topics in China Economic Research | [Click here to view the PDF.](./PDF/25春季中国经济专题笔记.pdf) <br>
  中国经济专题 | [点击此处查看PDF.](./PDF/25春季中国经济专题笔记.pdf)
- Intermediate Microeconomics <br>
  中级微观经济学
- Programming in Rust <br>
  Rust程序设计
- Orienteering and Hiking <br>
  定向与徒步运动
- Operating Systems (Honor Track) <br>
  操作系统 (实验班)
- Modern Astronomy <br>
  现代天文学

# 24-25-1

7 courses, 21 points in total.

- Public Junior German | [Click here to view the PDF.](./PDF/德语notes.pdf) <br>
  公共初级德语 | [点击此处查看PDF.](./PDF/德语notes.pdf)
- Econometrics | [Click here to view the PDF.](./PDF/计量经济学notes.pdf) <br>
  计量经济学 | [点击此处查看PDF.](./PDF/计量经济学notes.pdf)
- Software Engineering <br>
  软件工程
  - [The notes. 课程笔记.](./PDF/SE.pdf)
  - The Assignments. 课程作业.
    - [Homework 1](./PDF/SE-HW/SE-HW1.pdf)
    - [Homework 2](./PDF/SE-HW/SE-HW2.pdf)
    - [Homework 3](./PDF/SE-HW/SE-HW3.pdf)
- A Survey of Mao Tsetung Thoughts and Theory of Socialism with Chinese Charateristics <br>
  毛泽东思想和中国特色社会主义理论体系概论
- Software Analysis | [Check Prof. Xiong's Course Website](https://xiongyingfei.github.io/SA_new/2025/) <br>
  软件分析技术 | [查看课程网站](https://xiongyingfei.github.io/SA_new/2025/)
- Compiler Principles <br>
  编译原理
- Labor Practice for Electronics Engineering and Computer Science <br>
  信息科学技术劳动实践

# 23-24-3

2 courses, 3 points in total.

- Physical and Aesthetic course <br>
  体美
- Aural Culture and World Civilization <br>
  听觉文化与世界文明

# 23-24-2

9 courses, 24 points in total.

- Introduction to Object Oriented Technology | [Click here to view the final-term notes.](./PDF/OOP/期末复习.md) <br>
  面向对象技术引论 | [查看期末复习笔记](./PDF/OOP/期末复习.md)
- Comparative Constitutional Law <br>
  外国宪法
- Academic English Listening and Speaking <br>
  学术英语听说
- Algorithm Design and Analysis <br>
  算法设计与分析
- Information Theory <br>
  信息论
- History of Rome | [Click here to view the PDF.](./PDF/History_of_Rome.pdf) <br>
  罗马史 | [点击此处查看PDF.](./PDF/History_of_Rome.pdf)
- Software Foundations | [Check Prof. Xiong's Course Website](https://xiongyingfei.github.io/SF/2025/) <br>
  软件科学基础 | [查看课程网站](https://xiongyingfei.github.io/SF/2025/)
- Probability theory and statistics in Information science <br>
  信息学中的概率统计
- Intermediate Macroeconomics <br>
  中级宏观经济学

# 23-24-1

8 courses, 24 points in total.

- Human Sex, Reproduction and Health | [【三宝课X47小组期中作业】](https://www.bilibili.com/video/BV1nG411Y7qo/?share_source=copy_web&vd_source=47fec559f7b56937e0423d7b99b10fdd) <br>
  人类的性、生育与健康 | [【三宝课X47小组期中作业】](https://www.bilibili.com/video/BV1nG411Y7qo/?share_source=copy_web&vd_source=47fec559f7b56937e0423d7b99b10fdd)
- Music and Mathematics | [Click here to view the PDF.](./PDF/Music-And-Math.pdf) <br>
  音乐与数学 | [点击此处查看PDF.](./PDF/Music-And-Math.pdf)
- Data Structure and Algorithm (A) <br>
  数据结构与算法 (A)
- An Introduction to Marxist Basic Theory <br>
  马克思主义基本原理概论
- Introduction to Discrete Mathmatics <br>
  离散数学基础
- Principles of Economics <br>
  经济学原理
- Introduction to Computer Systems <br>
  计算机系统导论
- Labor Theory <br>
  新时代劳动理论

# 22-23-2

8 courses, 24 points in total.

- Text and Meaning: British and American Short Stories <br>
  英美短篇小说文本分析与鉴赏
- Introduction to Artificial Intelligence <br>
  人工智能引论
- Practice of Programming in C&C++ <br>
  程序设计实习
- Outline of Chinese Modern History <br>
  中国近现代史纲要
- Introduction to Xi Jinping Thought on Socialism with Chinese Characteristics for a New Era <br>
  习近平新时代中国特色社会主义思想概论
- Linear Algebra A (II) <br>
  线性代数A (II)
- Advanced Mathematics A (no.2) <br>
  高等数学A (二)
- Social practice and service learning, Part II <br>
  思想政治实践（下）

# 22-23-1

11 courses, 27 points in total.

- Introduction to Seismology <br>
  地震概论
- Introduction to Computation (A) <br>
  计算概论A
- Advanced Mathematics A (no.1) <br>
  高等数学A (一)
- Football <br>
  足球
- Physics for Information Sciences (1) <br>
  信息科学中的物理学 (上)
- Linear Algebra A (I) <br>
  线性代数A (I)
- Introduction to Information Science and Technique <br>
  信息科学技术概论
- An Introduction to Ideological & Moral Culture and Laws <br>
  思想道德修养与法律基础
- Events and Policies <br>
  形势与政策
- Military Theory <br>
  军事理论
- Social practice and service learning, Part I <br>
  思想政治实践（上）

TO BE CONTINUED ...
